FROM python:3.8

# Allow statements and log messages to immediately appear in the logs
ENV PYTHONUNBUFFERED True
ENV APP_HOME /stock_market

ENV FLASK_CONFIG testing

WORKDIR $APP_HOME

COPY requirements requirements
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements/dev.txt

COPY app app
COPY tests tests
COPY market.py config.py ./

# Run tests using pytest
CMD coverage run -m pytest tests -v && coverage report -m
